language: scala
scala:
   - 2.10.6
   
env:
  global:
    - CODECOV_TOKEN="4add9d27-1280-49e6-8c51-5e9aae30fbcf"

script:
   - sbt clean coverage test coverageReport
   
after_success:
- bash <(curl -s https://codecov.io/bash)
